## Understanding basic pytorch operations 

In this notebook we are going to understand the **absolute basics** of pytorch. 

But before doing anything we must know a few things about the building block of pytorch and those are **tensors**. Tensors are nothing but multidimensional scalers, which can be constants as well as variables. They are at the heart of any deep learning frameworks.

To list it out properly, we are going to do the following things, to get a clear understanding of pytorch.

- [ ] Create a basic tensor.
- [ ] Create a tensor from list.
- [ ] Create a tensor from numpy array.
- [ ] Create a tensor from uniform distribution.
- [ ] Create a tensor from random distribution.
- [ ] Change the data type of tensors.
- [ ] Check tensor size and shape.
- [ ] Tensor addition and multiplication.
- [ ] Indexing, Slicing, stacking and concatenating tensors.
- [ ] Creating cuda tensors.

Finally we are going to end with some exercises.

In [1]:
## First of importing the torch package ##

import torch
import numpy as np

Now since we are going to display the tensors everytime, it is best to define a utility function which will show a tensor's shape, its datatype and also its values. 

In [2]:
## Tensor Output utility function ##

def display(a):
    
    print('The type of the tensor is :' , a.type())
    
    print('The size of the tensor is :' , a.shape)
    
    print('The tensor is :\n{}'.format(a))

Now lets get on doing our basic foundations.

First lets create a simple tensor.

In [3]:
## Defining a simple tensor ##

a = torch.Tensor(2 , 3)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [2.5382e-09, 1.3297e+22, 1.0140e-11]])


Its pretty basic.

Now lets create another tensor from list.

In [4]:
## Defining tensor from list ##

a = torch.Tensor([[1 , 2 , 3],
                  [4 , 5 , 6]])

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[1., 2., 3.],
        [4., 5., 6.]])


With that out of the way, we are gonna make tensor from numpy array.

In [5]:
## Creating tensor from numpy ##

array_a = np.array([[1 , 2 , 3],
                    [4 , 5 , 6]])


a = torch.from_numpy(array_a)

display(a)

The type of the tensor is : torch.IntTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


What we can do next is make a tensor and have its type changed to float instead.

In [6]:
## Creating a tensor of type float ##

a = torch.tensor([[1 , 2 , 3],
                  [4 , 5 , 6]] , dtype = torch.float64)

display(a)

The type of the tensor is : torch.DoubleTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


Well the difference between `torch.Tensor` and `torch.tensor` is that `torch.Tensor` gives the data type float whereas `torch.tensor` automatically gives the dtype.

Now lets create a tensor from *uniform distribution*.

In [7]:
## Creating a tensor from uniform distribution ##

a = torch.rand(2 , 3)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[0.2408, 0.4635, 0.4043],
        [0.7165, 0.4961, 0.4149]])


Moving on we can create a tensor by taking elements from normal distribution.

In [8]:
## Creating a tensor from normal distribution ##

a = torch.randn(2 , 3)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[ 0.6702, -2.5331, -0.7480],
        [-1.3118, -2.2261, -1.3707]])


Now we are going to check the datatype of a tensor.

In [9]:
## Checking the datatype of tensor ##

a.type()

'torch.FloatTensor'

Also we can check the shape of the tensor by using `tensor.shape`.

In [10]:
## Checking the shape of the tensor ##

a.shape

torch.Size([2, 3])

Now we can also see the process of filling a tensor of certain size with certain values. 

Lets start by creating a matrix with only ones and only zeros. 

In [11]:
## Creating a matrix with zeros ##

a = torch.zeros(2 , 3)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
## Creating a matrix with ones ##

a = torch.ones(2 , 3)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Now lets make an empty tensor and then fill it with value of 5.

In [13]:
## Creating an empty matrix ##

a = torch.empty(2 , 3)

display(a)

print('--------------------------------------------------')

## Creating a tensor with values 5 ##

a = a.fill_(5)

display(a)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[4.3677e-05, 1.3384e+22, 8.5081e-07],
        [8.3385e-10, 1.0740e-05, 4.1540e+21]])
--------------------------------------------------
The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[5., 5., 5.],
        [5., 5., 5.]])


Now lets do simple addition with tensors.

In [14]:
## Simple addition of two tensors ##

a = torch.randn(2 , 3)

display(a)

print('--------------------------------------------------')

b = a + a

display(b)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[-0.4287,  0.3462, -0.3587],
        [ 0.3119, -0.9700,  0.8658]])
--------------------------------------------------
The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[-0.8574,  0.6923, -0.7174],
        [ 0.6238, -1.9400,  1.7317]])


Now lets showcase the multiplication of two tensors.

In [15]:
## Multiplication of two tensors ##

a = torch.empty(2 , 3)

a = a.fill_(1)

b = torch.mm(a , a.T)

display(b)

The type of the tensor is : torch.FloatTensor
The size of the tensor is : torch.Size([2, 2])
The tensor is :
tensor([[3., 3.],
        [3., 3.]])


All done!

Lets now do further operations like indexing and slicing.

In [16]:
## Indexing a tensor ##

a = torch.tensor([[1 , 2 , 3],
                  [4 , 5 , 6]])

display(a)

print('Indexed tensor :' , a[1 , 2])

The type of the tensor is : torch.LongTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[1, 2, 3],
        [4, 5, 6]])
Indexed tensor : tensor(6)


In [17]:
## Slicing a tensor ##

print('Sliced tensor :' , a[:1 , 0:2])

Sliced tensor : tensor([[1, 2]])


Now lets stack up two tensors.

In [18]:
## Stacking a tensor ##

b = torch.stack([a , a] , dim = 0)

display(b)

The type of the tensor is : torch.LongTensor
The size of the tensor is : torch.Size([2, 2, 3])
The tensor is :
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


Now lets concatenate two tensors.

In [19]:
## Concatenating a tensor ##

b = torch.cat([a , a] , dim = 1)

display(b)

The type of the tensor is : torch.LongTensor
The size of the tensor is : torch.Size([2, 6])
The tensor is :
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])


With that we have come to the beginning of using gpu in creating tensors.

In [20]:
## Checking if GPU is there ##

print(torch.cuda.is_available())

True


Now lets create a tensor and shift to the device.

In [21]:
## Setting the device ##

def get_device():
    
    if torch.cuda.is_available():
        
        return torch.device('cuda')
    
    return torch.device('cpu')

device = get_device()


## Creating a tensor ##

a = torch.randn(2 , 3)

## Shift the device ##

a = a.to(device)

display(a)

The type of the tensor is : torch.cuda.FloatTensor
The size of the tensor is : torch.Size([2, 3])
The tensor is :
tensor([[-0.8001, -2.9121,  0.3484],
        [-0.0601,  0.3556,  0.9136]], device='cuda:0')


With that we come to the end of this notebook.

If you want to learn about how to install pytorch please check the `pytorch_basic.ipynb` notebook.