### Basic Linear Regression with Pytorch

So, in this notebook we are going to exercise our basic knowledge with implementation of own created Linear Regression using the basic syntax of Pytorch we learnt in the previous notebook.

In [1]:
#Importing pytorch
import torch

import numpy as np #importing numpy

Now, we can download a dataset easily from Kaggle and implement Linear Regression for sure, but in this basic level code lets create our own simple dataset and then carry on.

So, we are going to have 5 samples of data with 3 features each. Furthermore, we are going to pop out 2 outputs.

Lets do that first.

In [2]:
##Set the inputs

inputs = torch.tensor([[33. , 22. , 57.],
                       [45. , 37. , 89.],
                       [64. , 25. , 68.],
                       [37. , 31. , 42.],
                       [29. , 20. , 41.]])

inputs = inputs / torch.max(inputs)

inputs

tensor([[0.3708, 0.2472, 0.6404],
        [0.5056, 0.4157, 1.0000],
        [0.7191, 0.2809, 0.7640],
        [0.4157, 0.3483, 0.4719],
        [0.3258, 0.2247, 0.4607]])

In [3]:
##Set the targets

targets = torch.tensor([[45. , 70.],
                        [27. , 57.],
                        [34. , 77.],
                        [41. , 68.], 
                        [37. , 81.]])

targets

tensor([[45., 70.],
        [27., 57.],
        [34., 77.],
        [41., 68.],
        [37., 81.]])

Voila! We have created our datasets.

Now, a Linear Regression model is based on the equation of straight line, i.e., <code>y = mx + c</code>.

So we need to set our weights and biases.
Lets do that.

For this dataset, our weights would be of the shape (2,3) and our biases would be of the shape 2.

Lets randomly define them to start our model.

In [4]:
w = torch.randn(2 , 3 , requires_grad  = True)

b = torch.randn(2 , requires_grad = True)

Done!

The <code>requires_grad = True</code> sets the w and b for backprop.

Now lets define our model and then define our loss function, thereafter start training.

In [5]:
##defining Linear Regression model

def model(inputs):
    return inputs @ w.t() + b

In [6]:
##defining Cost Function

def mse(t1 , t2):
    
    diff = t2 - t1
    
    return torch.sum(diff * diff) / diff.numel()

In [7]:
#Generate predictions
preds = model(inputs)
print(preds)

tensor([[-1.3214,  1.7636],
        [-1.3020,  2.2316],
        [-1.5479,  2.9163],
        [-1.1105,  1.8982],
        [-1.2462,  1.6030]], grad_fn=<AddBackward0>)


In [8]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(3126.3918, grad_fn=<DivBackward0>)


In [9]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(3126.3918, grad_fn=<DivBackward0>)


In [10]:
# Compute gradients
loss.backward()

In [11]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.6430,  1.6078, -0.4585],
        [ 3.2840, -0.0061,  0.0731]], requires_grad=True)
tensor([[-17.4033, -11.2928, -24.5240],
        [-31.9236, -20.2625, -44.5688]])


Lets now start training our model and see how it fetches!

In [12]:
for epochs in range(100):
    
    
    pred = model(inputs)
    
    pred.requires_grad_(True)
    pred.retain_grad()
    
    loss = mse(pred , targets)
    
    #w.retain_grad()
    #b.retain_grad()
    
    loss.backward() #backprop
    
    #print(loss.item())
    
    #print(w.grad)
    
    with torch.no_grad():
    
        w -= (1e-3 * w.grad)
        b -= (1e-3 * b.grad)
    
        w.grad.zero_()
        b.grad.zero_()

    
    print('Epoch : [{} / {}] --> Loss : {}'.format(epochs + 1, 100 , loss.item()))

Epoch : [1 / 100] --> Loss : 3126.391845703125
Epoch : [2 / 100] --> Loss : 3105.240234375
Epoch : [3 / 100] --> Loss : 3094.730224609375
Epoch : [4 / 100] --> Loss : 3084.25732421875
Epoch : [5 / 100] --> Loss : 3073.82177734375
Epoch : [6 / 100] --> Loss : 3063.423095703125
Epoch : [7 / 100] --> Loss : 3053.061279296875
Epoch : [8 / 100] --> Loss : 3042.736572265625
Epoch : [9 / 100] --> Loss : 3032.4482421875
Epoch : [10 / 100] --> Loss : 3022.1962890625
Epoch : [11 / 100] --> Loss : 3011.98095703125
Epoch : [12 / 100] --> Loss : 3001.8017578125
Epoch : [13 / 100] --> Loss : 2991.65869140625
Epoch : [14 / 100] --> Loss : 2981.5517578125
Epoch : [15 / 100] --> Loss : 2971.48095703125
Epoch : [16 / 100] --> Loss : 2961.445556640625
Epoch : [17 / 100] --> Loss : 2951.44580078125
Epoch : [18 / 100] --> Loss : 2941.481201171875
Epoch : [19 / 100] --> Loss : 2931.552001953125
Epoch : [20 / 100] --> Loss : 2921.65869140625
Epoch : [21 / 100] --> Loss : 2911.80029296875
Epoch : [22 / 100] -